### ISSUE TITLE
Scope errors

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/wand#16]
It looks like the change in #12 have borked our scope with `this`. We are running into this error on [line 19](https://github.com/codeforamerica/wand/blob/master/src/js/wand.js#L19):

```
TypeError: undefined is not an object (evaluating 'this.nodes.length')
```

**Comment by bsmithgall** [comment]
I think I fixed that. Can you make sure you are up to date with master?

**Comment by mapsam** [comment]
Just tested with a fresh clone of master and still getting the error. We managed to [fix](https://github.com/codeforamerica/wand/blob/ui/src/js/wand.js#L28) with bringing back `Wand.prototype.etc` so we have access to the `Wand` object throughout our major functions. Seems like this method is relatively similar to the original version though.

**Comment by mapsam** [comment]
:clap:
